05-25 17:20:08 jdbc[1]: SQLException
org.h2.jdbc.JdbcSQLException: Column count does not match; SQL statement: INSERT INTO SEMINAR VALUES('0001-J.PROG',999,'Java Grundlagen und Objektorientierung',5,'Java für Programmierer','J.PROG')
INSERT INTO SEMINAR VALUES('0002-J.AUFB',999,'Weiterführende Konzepte in Swing, Datenbanken, RMI, Threading',5,'Java Aufbaukurs','J.AUFB')
INSERT INTO SEMINAR VALUES('0003-J.SERV',999,'Grundlagen der Servlet Programmierung, Java Server Pages, Taglibs',3,'Servlets und Java Server Pages JSP','J.SERV')
INSERT INTO SEMINAR VALUES('0004-X.EINF',999,'XML Grundlagen, XPath, Formatierung mit XSLT',3,'XML Einführung','X.EINF')
INSERT INTO SEMINAR VALUES('0005-X.JAVA',999,'Bearbeiten von XML Dokumenten in Java, Transformation, Mapping',2,'XML mit Java','X.JAVA') [21S02-46]
	at org.h2.message.Message.addSQL(Message.java:348)
	at org.h2.command.Parser.prepareCommand(Parser.java:213)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:966)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:143)
	at org.h2.server.web.AppThread.getResult(AppThread.java:941)
	at org.h2.server.web.AppThread.query(AppThread.java:611)
	at org.h2.server.web.AppThread.process(AppThread.java:71)
	at org.h2.server.web.WebServerThread.run(WebServerThread.java:127)
Caused by: org.h2.jdbc.JdbcSQLException: Column count does not match [21S02-46]
	at org.h2.message.Message.getSQLException(Message.java:65)
	at org.h2.message.Message.getSQLException(Message.java:47)
	at org.h2.message.Message.getSQLException(Message.java:86)
	at org.h2.command.dml.Insert.prepare(Insert.java:175)
	at org.h2.command.Parser.prepareCommand(Parser.java:193)
	... 8 more
05-25 17:20:41 jdbc[1]: SQLException
org.h2.jdbc.JdbcSQLException: Column count does not match; SQL statement: INSERT INTO SEMINAR VALUES('0001-J.PROG',999,'Java Grundlagen und Objektorientierung',5,'Java für Programmierer','J.PROG') [21S02-46]
	at org.h2.message.Message.addSQL(Message.java:348)
	at org.h2.command.Parser.prepareCommand(Parser.java:213)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:966)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:143)
	at org.h2.server.web.AppThread.getResult(AppThread.java:941)
	at org.h2.server.web.AppThread.query(AppThread.java:611)
	at org.h2.server.web.AppThread.process(AppThread.java:71)
	at org.h2.server.web.WebServerThread.run(WebServerThread.java:127)
Caused by: org.h2.jdbc.JdbcSQLException: Column count does not match [21S02-46]
	at org.h2.message.Message.getSQLException(Message.java:65)
	at org.h2.message.Message.getSQLException(Message.java:47)
	at org.h2.message.Message.getSQLException(Message.java:86)
	at org.h2.command.dml.Insert.prepare(Insert.java:175)
	at org.h2.command.Parser.prepareCommand(Parser.java:193)
	... 8 more
05-25 17:20:41 jdbc[1]: SQLException
org.h2.jdbc.JdbcSQLException: Column count does not match; SQL statement: INSERT INTO SEMINAR VALUES('0002-J.AUFB',999,'Weiterführende Konzepte in Swing, Datenbanken, RMI, Threading',5,'Java Aufbaukurs','J.AUFB') [21S02-46]
	at org.h2.message.Message.addSQL(Message.java:348)
	at org.h2.command.Parser.prepareCommand(Parser.java:213)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:966)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:143)
	at org.h2.server.web.AppThread.getResult(AppThread.java:941)
	at org.h2.server.web.AppThread.query(AppThread.java:611)
	at org.h2.server.web.AppThread.process(AppThread.java:71)
	at org.h2.server.web.WebServerThread.run(WebServerThread.java:127)
Caused by: org.h2.jdbc.JdbcSQLException: Column count does not match [21S02-46]
	at org.h2.message.Message.getSQLException(Message.java:65)
	at org.h2.message.Message.getSQLException(Message.java:47)
	at org.h2.message.Message.getSQLException(Message.java:86)
	at org.h2.command.dml.Insert.prepare(Insert.java:175)
	at org.h2.command.Parser.prepareCommand(Parser.java:193)
	... 8 more
05-25 17:20:41 jdbc[1]: SQLException
org.h2.jdbc.JdbcSQLException: Column count does not match; SQL statement: INSERT INTO SEMINAR VALUES('0003-J.SERV',999,'Grundlagen der Servlet Programmierung, Java Server Pages, Taglibs',3,'Servlets und Java Server Pages JSP','J.SERV') [21S02-46]
	at org.h2.message.Message.addSQL(Message.java:348)
	at org.h2.command.Parser.prepareCommand(Parser.java:213)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:966)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:143)
	at org.h2.server.web.AppThread.getResult(AppThread.java:941)
	at org.h2.server.web.AppThread.query(AppThread.java:611)
	at org.h2.server.web.AppThread.process(AppThread.java:71)
	at org.h2.server.web.WebServerThread.run(WebServerThread.java:127)
Caused by: org.h2.jdbc.JdbcSQLException: Column count does not match [21S02-46]
	at org.h2.message.Message.getSQLException(Message.java:65)
	at org.h2.message.Message.getSQLException(Message.java:47)
	at org.h2.message.Message.getSQLException(Message.java:86)
	at org.h2.command.dml.Insert.prepare(Insert.java:175)
	at org.h2.command.Parser.prepareCommand(Parser.java:193)
	... 8 more
05-25 17:20:41 jdbc[1]: SQLException
org.h2.jdbc.JdbcSQLException: Column count does not match; SQL statement: INSERT INTO SEMINAR VALUES('0004-X.EINF',999,'XML Grundlagen, XPath, Formatierung mit XSLT',3,'XML Einführung','X.EINF') [21S02-46]
	at org.h2.message.Message.addSQL(Message.java:348)
	at org.h2.command.Parser.prepareCommand(Parser.java:213)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:966)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:143)
	at org.h2.server.web.AppThread.getResult(AppThread.java:941)
	at org.h2.server.web.AppThread.query(AppThread.java:611)
	at org.h2.server.web.AppThread.process(AppThread.java:71)
	at org.h2.server.web.WebServerThread.run(WebServerThread.java:127)
Caused by: org.h2.jdbc.JdbcSQLException: Column count does not match [21S02-46]
	at org.h2.message.Message.getSQLException(Message.java:65)
	at org.h2.message.Message.getSQLException(Message.java:47)
	at org.h2.message.Message.getSQLException(Message.java:86)
	at org.h2.command.dml.Insert.prepare(Insert.java:175)
	at org.h2.command.Parser.prepareCommand(Parser.java:193)
	... 8 more
05-25 17:20:41 jdbc[1]: SQLException
org.h2.jdbc.JdbcSQLException: Column count does not match; SQL statement: INSERT INTO SEMINAR VALUES('0005-X.JAVA',999,'Bearbeiten von XML Dokumenten in Java, Transformation, Mapping',2,'XML mit Java','X.JAVA') [21S02-46]
	at org.h2.message.Message.addSQL(Message.java:348)
	at org.h2.command.Parser.prepareCommand(Parser.java:213)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:966)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:143)
	at org.h2.server.web.AppThread.getResult(AppThread.java:941)
	at org.h2.server.web.AppThread.query(AppThread.java:611)
	at org.h2.server.web.AppThread.process(AppThread.java:71)
	at org.h2.server.web.WebServerThread.run(WebServerThread.java:127)
Caused by: org.h2.jdbc.JdbcSQLException: Column count does not match [21S02-46]
	at org.h2.message.Message.getSQLException(Message.java:65)
	at org.h2.message.Message.getSQLException(Message.java:47)
	at org.h2.message.Message.getSQLException(Message.java:86)
	at org.h2.command.dml.Insert.prepare(Insert.java:175)
	at org.h2.command.Parser.prepareCommand(Parser.java:193)
	... 8 more
05-25 17:47:58 database: opening C:\Java\h2-1.0\data\aufbau
org.h2.jdbc.JdbcSQLException: Database may be already open: Locked by another process [90020-46]
	at org.h2.message.Message.getSQLException(Message.java:65)
	at org.h2.message.Message.getSQLException(Message.java:47)
	at org.h2.store.FileLock.error(FileLock.java:310)
	at org.h2.store.FileLock.lockFile(FileLock.java:171)
	at org.h2.store.FileLock.lock(FileLock.java:65)
	at org.h2.engine.Database.open(Database.java:423)
	at org.h2.engine.Database.<init>(Database.java:378)
	at org.h2.engine.Engine.openSession(Engine.java:49)
	at org.h2.engine.Engine.getSession(Engine.java:92)
	at org.h2.engine.Session.createSession(Session.java:140)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:923)
	at org.h2.Driver.connect(Driver.java:52)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at de.oio.aufbau.jdbc.SimpleSelect.main(SimpleSelect.java:22)
05-25 17:53:02 database: opening C:\Java\h2-1.0\data\aufbau
org.h2.jdbc.JdbcSQLException: Database may be already open: Locked by another process [90020-46]
	at org.h2.message.Message.getSQLException(Message.java:65)
	at org.h2.message.Message.getSQLException(Message.java:47)
	at org.h2.store.FileLock.error(FileLock.java:310)
	at org.h2.store.FileLock.lockFile(FileLock.java:171)
	at org.h2.store.FileLock.lock(FileLock.java:65)
	at org.h2.engine.Database.open(Database.java:423)
	at org.h2.engine.Database.<init>(Database.java:378)
	at org.h2.engine.Engine.openSession(Engine.java:49)
	at org.h2.engine.Engine.getSession(Engine.java:92)
	at org.h2.engine.Session.createSession(Session.java:140)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:923)
	at org.h2.Driver.connect(Driver.java:52)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at de.oio.aufbau.jdbc.SimpleSelect.main(SimpleSelect.java:22)
05-25 17:55:57 jdbc[0]: SQLException
org.h2.jdbc.JdbcSQLException: Table PERSON not found; SQL statement: INSERT INTO person VALUES (NULL, '0001-J.PROG','Zwink','Daniel') [42S02-46]
	at org.h2.message.Message.addSQL(Message.java:348)
	at org.h2.command.Parser.parse(Parser.java:227)
	at org.h2.command.Parser.prepareCommand(Parser.java:192)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:966)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:105)
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:603)
	at de.oio.aufbau.jdbc.ExtendedJdbc.doBatch(ExtendedJdbc.java:96)
	at de.oio.aufbau.jdbc.ExtendedJdbc.main(ExtendedJdbc.java:189)
Caused by: org.h2.jdbc.JdbcSQLException: Table PERSON not found [42S02-46]
	at org.h2.message.Message.getSQLException(Message.java:65)
	at org.h2.message.Message.getSQLException(Message.java:47)
	at org.h2.schema.Schema.getTableOrView(Schema.java:203)
	at org.h2.command.Parser.parseInsert(Parser.java:697)
	at org.h2.command.Parser.parse(Parser.java:316)
	at org.h2.command.Parser.parse(Parser.java:221)
	... 8 more
05-25 17:55:57 jdbc[0]: SQLException
org.h2.jdbc.JdbcSQLException: Table PERSON not found; SQL statement: INSERT INTO person VALUES (NULL, '0001-J.PROG','Zwink','Daniel') [42S02-46]
	at org.h2.message.Message.addSQL(Message.java:348)
	at org.h2.command.Parser.parse(Parser.java:227)
	at org.h2.command.Parser.prepareCommand(Parser.java:192)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:966)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:105)
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:603)
	at de.oio.aufbau.jdbc.ExtendedJdbc.doBatch(ExtendedJdbc.java:96)
	at de.oio.aufbau.jdbc.ExtendedJdbc.main(ExtendedJdbc.java:189)
Caused by: org.h2.jdbc.JdbcSQLException: Table PERSON not found [42S02-46]
	at org.h2.message.Message.getSQLException(Message.java:65)
	at org.h2.message.Message.getSQLException(Message.java:47)
	at org.h2.schema.Schema.getTableOrView(Schema.java:203)
	at org.h2.command.Parser.parseInsert(Parser.java:697)
	at org.h2.command.Parser.parse(Parser.java:316)
	at org.h2.command.Parser.parse(Parser.java:221)
	... 8 more
05-25 17:55:57 jdbc[0]: SQLException
org.h2.jdbc.JdbcSQLException: Table PERSON not found; SQL statement: INSERT INTO person VALUES (NULL, '0001-J.PROG','Mustermann','Max') [42S02-46]
	at org.h2.message.Message.addSQL(Message.java:348)
	at org.h2.command.Parser.parse(Parser.java:227)
	at org.h2.command.Parser.prepareCommand(Parser.java:192)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:966)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:105)
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:603)
	at de.oio.aufbau.jdbc.ExtendedJdbc.doBatch(ExtendedJdbc.java:96)
	at de.oio.aufbau.jdbc.ExtendedJdbc.main(ExtendedJdbc.java:189)
Caused by: org.h2.jdbc.JdbcSQLException: Table PERSON not found [42S02-46]
	at org.h2.message.Message.getSQLException(Message.java:65)
	at org.h2.message.Message.getSQLException(Message.java:47)
	at org.h2.schema.Schema.getTableOrView(Schema.java:203)
	at org.h2.command.Parser.parseInsert(Parser.java:697)
	at org.h2.command.Parser.parse(Parser.java:316)
	at org.h2.command.Parser.parse(Parser.java:221)
	... 8 more
05-25 17:55:57 jdbc[0]: SQLException
org.h2.jdbc.JdbcSQLException: Table PERSON not found; SQL statement: INSERT INTO person VALUES (NULL, '0001-J.PROG','Mustermann','Max') [42S02-46]
	at org.h2.message.Message.addSQL(Message.java:348)
	at org.h2.command.Parser.parse(Parser.java:227)
	at org.h2.command.Parser.prepareCommand(Parser.java:192)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:966)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:105)
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:603)
	at de.oio.aufbau.jdbc.ExtendedJdbc.doBatch(ExtendedJdbc.java:96)
	at de.oio.aufbau.jdbc.ExtendedJdbc.main(ExtendedJdbc.java:189)
Caused by: org.h2.jdbc.JdbcSQLException: Table PERSON not found [42S02-46]
	at org.h2.message.Message.getSQLException(Message.java:65)
	at org.h2.message.Message.getSQLException(Message.java:47)
	at org.h2.schema.Schema.getTableOrView(Schema.java:203)
	at org.h2.command.Parser.parseInsert(Parser.java:697)
	at org.h2.command.Parser.parse(Parser.java:316)
	at org.h2.command.Parser.parse(Parser.java:221)
	... 8 more
05-25 17:55:57 jdbc[0]: SQLException
org.h2.jdbc.JdbcSQLException: Table PERSON not found; SQL statement: INSERT INTO person VALUES (NULL, '0001-J.PROG','Schmidt','Michael') [42S02-46]
	at org.h2.message.Message.addSQL(Message.java:348)
	at org.h2.command.Parser.parse(Parser.java:227)
	at org.h2.command.Parser.prepareCommand(Parser.java:192)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:966)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:105)
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:603)
	at de.oio.aufbau.jdbc.ExtendedJdbc.doBatch(ExtendedJdbc.java:96)
	at de.oio.aufbau.jdbc.ExtendedJdbc.main(ExtendedJdbc.java:189)
Caused by: org.h2.jdbc.JdbcSQLException: Table PERSON not found [42S02-46]
	at org.h2.message.Message.getSQLException(Message.java:65)
	at org.h2.message.Message.getSQLException(Message.java:47)
	at org.h2.schema.Schema.getTableOrView(Schema.java:203)
	at org.h2.command.Parser.parseInsert(Parser.java:697)
	at org.h2.command.Parser.parse(Parser.java:316)
	at org.h2.command.Parser.parse(Parser.java:221)
	... 8 more
05-25 17:55:57 jdbc[0]: SQLException
org.h2.jdbc.JdbcSQLException: Table PERSON not found; SQL statement: INSERT INTO person VALUES (NULL, '0001-J.PROG','Schmidt','Michael') [42S02-46]
	at org.h2.message.Message.addSQL(Message.java:348)
	at org.h2.command.Parser.parse(Parser.java:227)
	at org.h2.command.Parser.prepareCommand(Parser.java:192)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:966)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:105)
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:603)
	at de.oio.aufbau.jdbc.ExtendedJdbc.doBatch(ExtendedJdbc.java:96)
	at de.oio.aufbau.jdbc.ExtendedJdbc.main(ExtendedJdbc.java:189)
Caused by: org.h2.jdbc.JdbcSQLException: Table PERSON not found [42S02-46]
	at org.h2.message.Message.getSQLException(Message.java:65)
	at org.h2.message.Message.getSQLException(Message.java:47)
	at org.h2.schema.Schema.getTableOrView(Schema.java:203)
	at org.h2.command.Parser.parseInsert(Parser.java:697)
	at org.h2.command.Parser.parse(Parser.java:316)
	at org.h2.command.Parser.parse(Parser.java:221)
	... 8 more
05-25 17:55:57 jdbc[0]: SQLException
java.sql.BatchUpdateException
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:614)
	at de.oio.aufbau.jdbc.ExtendedJdbc.doBatch(ExtendedJdbc.java:96)
	at de.oio.aufbau.jdbc.ExtendedJdbc.main(ExtendedJdbc.java:189)
05-25 17:55:57 jdbc[0]: SQLException
org.h2.jdbc.JdbcSQLException: Table PERSON not found; SQL statement: INSERT INTO person VALUES (NULL, '0001-J.PROG','Zwink','Daniel') [42S02-46]
	at org.h2.message.Message.addSQL(Message.java:348)
	at org.h2.command.Parser.parse(Parser.java:227)
	at org.h2.command.Parser.prepareCommand(Parser.java:192)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:966)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:105)
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:603)
	at de.oio.aufbau.jdbc.ExtendedJdbc.doTransaction(ExtendedJdbc.java:126)
	at de.oio.aufbau.jdbc.ExtendedJdbc.main(ExtendedJdbc.java:190)
Caused by: org.h2.jdbc.JdbcSQLException: Table PERSON not found [42S02-46]
	at org.h2.message.Message.getSQLException(Message.java:65)
	at org.h2.message.Message.getSQLException(Message.java:47)
	at org.h2.schema.Schema.getTableOrView(Schema.java:203)
	at org.h2.command.Parser.parseInsert(Parser.java:697)
	at org.h2.command.Parser.parse(Parser.java:316)
	at org.h2.command.Parser.parse(Parser.java:221)
	... 8 more
05-25 17:55:57 jdbc[0]: SQLException
org.h2.jdbc.JdbcSQLException: Table PERSON not found; SQL statement: INSERT INTO person VALUES (NULL, '0001-J.PROG','Zwink','Daniel') [42S02-46]
	at org.h2.message.Message.addSQL(Message.java:348)
	at org.h2.command.Parser.parse(Parser.java:227)
	at org.h2.command.Parser.prepareCommand(Parser.java:192)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:966)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:105)
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:603)
	at de.oio.aufbau.jdbc.ExtendedJdbc.doTransaction(ExtendedJdbc.java:126)
	at de.oio.aufbau.jdbc.ExtendedJdbc.main(ExtendedJdbc.java:190)
Caused by: org.h2.jdbc.JdbcSQLException: Table PERSON not found [42S02-46]
	at org.h2.message.Message.getSQLException(Message.java:65)
	at org.h2.message.Message.getSQLException(Message.java:47)
	at org.h2.schema.Schema.getTableOrView(Schema.java:203)
	at org.h2.command.Parser.parseInsert(Parser.java:697)
	at org.h2.command.Parser.parse(Parser.java:316)
	at org.h2.command.Parser.parse(Parser.java:221)
	... 8 more
05-25 17:55:57 jdbc[0]: SQLException
org.h2.jdbc.JdbcSQLException: Table PERSON not found; SQL statement: INSERT INTO person VALUES (NULL, '0001-J.PROG','Mustermann','Max') [42S02-46]
	at org.h2.message.Message.addSQL(Message.java:348)
	at org.h2.command.Parser.parse(Parser.java:227)
	at org.h2.command.Parser.prepareCommand(Parser.java:192)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:966)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:105)
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:603)
	at de.oio.aufbau.jdbc.ExtendedJdbc.doTransaction(ExtendedJdbc.java:126)
	at de.oio.aufbau.jdbc.ExtendedJdbc.main(ExtendedJdbc.java:190)
Caused by: org.h2.jdbc.JdbcSQLException: Table PERSON not found [42S02-46]
	at org.h2.message.Message.getSQLException(Message.java:65)
	at org.h2.message.Message.getSQLException(Message.java:47)
	at org.h2.schema.Schema.getTableOrView(Schema.java:203)
	at org.h2.command.Parser.parseInsert(Parser.java:697)
	at org.h2.command.Parser.parse(Parser.java:316)
	at org.h2.command.Parser.parse(Parser.java:221)
	... 8 more
05-25 17:55:57 jdbc[0]: SQLException
org.h2.jdbc.JdbcSQLException: Table PERSON not found; SQL statement: INSERT INTO person VALUES (NULL, '0001-J.PROG','Mustermann','Max') [42S02-46]
	at org.h2.message.Message.addSQL(Message.java:348)
	at org.h2.command.Parser.parse(Parser.java:227)
	at org.h2.command.Parser.prepareCommand(Parser.java:192)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:966)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:105)
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:603)
	at de.oio.aufbau.jdbc.ExtendedJdbc.doTransaction(ExtendedJdbc.java:126)
	at de.oio.aufbau.jdbc.ExtendedJdbc.main(ExtendedJdbc.java:190)
Caused by: org.h2.jdbc.JdbcSQLException: Table PERSON not found [42S02-46]
	at org.h2.message.Message.getSQLException(Message.java:65)
	at org.h2.message.Message.getSQLException(Message.java:47)
	at org.h2.schema.Schema.getTableOrView(Schema.java:203)
	at org.h2.command.Parser.parseInsert(Parser.java:697)
	at org.h2.command.Parser.parse(Parser.java:316)
	at org.h2.command.Parser.parse(Parser.java:221)
	... 8 more
05-25 17:55:57 jdbc[0]: SQLException
org.h2.jdbc.JdbcSQLException: Table PERSON not found; SQL statement: INSERT INTO person VALUES (NULL, '0001-J.PROG','Schmidt','Michael') [42S02-46]
	at org.h2.message.Message.addSQL(Message.java:348)
	at org.h2.command.Parser.parse(Parser.java:227)
	at org.h2.command.Parser.prepareCommand(Parser.java:192)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:966)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:105)
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:603)
	at de.oio.aufbau.jdbc.ExtendedJdbc.doTransaction(ExtendedJdbc.java:126)
	at de.oio.aufbau.jdbc.ExtendedJdbc.main(ExtendedJdbc.java:190)
Caused by: org.h2.jdbc.JdbcSQLException: Table PERSON not found [42S02-46]
	at org.h2.message.Message.getSQLException(Message.java:65)
	at org.h2.message.Message.getSQLException(Message.java:47)
	at org.h2.schema.Schema.getTableOrView(Schema.java:203)
	at org.h2.command.Parser.parseInsert(Parser.java:697)
	at org.h2.command.Parser.parse(Parser.java:316)
	at org.h2.command.Parser.parse(Parser.java:221)
	... 8 more
05-25 17:55:57 jdbc[0]: SQLException
org.h2.jdbc.JdbcSQLException: Table PERSON not found; SQL statement: INSERT INTO person VALUES (NULL, '0001-J.PROG','Schmidt','Michael') [42S02-46]
	at org.h2.message.Message.addSQL(Message.java:348)
	at org.h2.command.Parser.parse(Parser.java:227)
	at org.h2.command.Parser.prepareCommand(Parser.java:192)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:966)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:105)
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:603)
	at de.oio.aufbau.jdbc.ExtendedJdbc.doTransaction(ExtendedJdbc.java:126)
	at de.oio.aufbau.jdbc.ExtendedJdbc.main(ExtendedJdbc.java:190)
Caused by: org.h2.jdbc.JdbcSQLException: Table PERSON not found [42S02-46]
	at org.h2.message.Message.getSQLException(Message.java:65)
	at org.h2.message.Message.getSQLException(Message.java:47)
	at org.h2.schema.Schema.getTableOrView(Schema.java:203)
	at org.h2.command.Parser.parseInsert(Parser.java:697)
	at org.h2.command.Parser.parse(Parser.java:316)
	at org.h2.command.Parser.parse(Parser.java:221)
	... 8 more
05-25 17:55:57 jdbc[0]: SQLException
java.sql.BatchUpdateException
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:614)
	at de.oio.aufbau.jdbc.ExtendedJdbc.doTransaction(ExtendedJdbc.java:126)
	at de.oio.aufbau.jdbc.ExtendedJdbc.main(ExtendedJdbc.java:190)
05-25 18:02:52 jdbc[0]: SQLException
org.h2.jdbc.JdbcSQLException: Column count does not match; SQL statement: INSERT INTO person VALUES ('0001-J.PROG','Zwink','Daniel') [21S02-46]
	at org.h2.message.Message.addSQL(Message.java:348)
	at org.h2.command.Parser.prepareCommand(Parser.java:213)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:966)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:105)
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:603)
	at de.oio.aufbau.jdbc.ExtendedJdbc.doBatch(ExtendedJdbc.java:96)
	at de.oio.aufbau.jdbc.ExtendedJdbc.main(ExtendedJdbc.java:189)
Caused by: org.h2.jdbc.JdbcSQLException: Column count does not match [21S02-46]
	at org.h2.message.Message.getSQLException(Message.java:65)
	at org.h2.message.Message.getSQLException(Message.java:47)
	at org.h2.message.Message.getSQLException(Message.java:86)
	at org.h2.command.dml.Insert.prepare(Insert.java:175)
	at org.h2.command.Parser.prepareCommand(Parser.java:193)
	... 7 more
05-25 18:02:52 jdbc[0]: SQLException
org.h2.jdbc.JdbcSQLException: Column count does not match; SQL statement: INSERT INTO person VALUES ('0001-J.PROG','Zwink','Daniel') [21S02-46]
	at org.h2.message.Message.addSQL(Message.java:348)
	at org.h2.command.Parser.prepareCommand(Parser.java:213)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:966)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:105)
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:603)
	at de.oio.aufbau.jdbc.ExtendedJdbc.doBatch(ExtendedJdbc.java:96)
	at de.oio.aufbau.jdbc.ExtendedJdbc.main(ExtendedJdbc.java:189)
Caused by: org.h2.jdbc.JdbcSQLException: Column count does not match [21S02-46]
	at org.h2.message.Message.getSQLException(Message.java:65)
	at org.h2.message.Message.getSQLException(Message.java:47)
	at org.h2.message.Message.getSQLException(Message.java:86)
	at org.h2.command.dml.Insert.prepare(Insert.java:175)
	at org.h2.command.Parser.prepareCommand(Parser.java:193)
	... 7 more
05-25 18:02:52 jdbc[0]: SQLException
org.h2.jdbc.JdbcSQLException: Column count does not match; SQL statement: INSERT INTO person VALUES ('0001-J.PROG','Mustermann','Max') [21S02-46]
	at org.h2.message.Message.addSQL(Message.java:348)
	at org.h2.command.Parser.prepareCommand(Parser.java:213)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:966)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:105)
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:603)
	at de.oio.aufbau.jdbc.ExtendedJdbc.doBatch(ExtendedJdbc.java:96)
	at de.oio.aufbau.jdbc.ExtendedJdbc.main(ExtendedJdbc.java:189)
Caused by: org.h2.jdbc.JdbcSQLException: Column count does not match [21S02-46]
	at org.h2.message.Message.getSQLException(Message.java:65)
	at org.h2.message.Message.getSQLException(Message.java:47)
	at org.h2.message.Message.getSQLException(Message.java:86)
	at org.h2.command.dml.Insert.prepare(Insert.java:175)
	at org.h2.command.Parser.prepareCommand(Parser.java:193)
	... 7 more
05-25 18:02:52 jdbc[0]: SQLException
org.h2.jdbc.JdbcSQLException: Column count does not match; SQL statement: INSERT INTO person VALUES ('0001-J.PROG','Mustermann','Max') [21S02-46]
	at org.h2.message.Message.addSQL(Message.java:348)
	at org.h2.command.Parser.prepareCommand(Parser.java:213)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:966)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:105)
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:603)
	at de.oio.aufbau.jdbc.ExtendedJdbc.doBatch(ExtendedJdbc.java:96)
	at de.oio.aufbau.jdbc.ExtendedJdbc.main(ExtendedJdbc.java:189)
Caused by: org.h2.jdbc.JdbcSQLException: Column count does not match [21S02-46]
	at org.h2.message.Message.getSQLException(Message.java:65)
	at org.h2.message.Message.getSQLException(Message.java:47)
	at org.h2.message.Message.getSQLException(Message.java:86)
	at org.h2.command.dml.Insert.prepare(Insert.java:175)
	at org.h2.command.Parser.prepareCommand(Parser.java:193)
	... 7 more
05-25 18:02:52 jdbc[0]: SQLException
org.h2.jdbc.JdbcSQLException: Column count does not match; SQL statement: INSERT INTO person VALUES ('0001-J.PROG','Schmidt','Michael') [21S02-46]
	at org.h2.message.Message.addSQL(Message.java:348)
	at org.h2.command.Parser.prepareCommand(Parser.java:213)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:966)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:105)
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:603)
	at de.oio.aufbau.jdbc.ExtendedJdbc.doBatch(ExtendedJdbc.java:96)
	at de.oio.aufbau.jdbc.ExtendedJdbc.main(ExtendedJdbc.java:189)
Caused by: org.h2.jdbc.JdbcSQLException: Column count does not match [21S02-46]
	at org.h2.message.Message.getSQLException(Message.java:65)
	at org.h2.message.Message.getSQLException(Message.java:47)
	at org.h2.message.Message.getSQLException(Message.java:86)
	at org.h2.command.dml.Insert.prepare(Insert.java:175)
	at org.h2.command.Parser.prepareCommand(Parser.java:193)
	... 7 more
05-25 18:02:52 jdbc[0]: SQLException
org.h2.jdbc.JdbcSQLException: Column count does not match; SQL statement: INSERT INTO person VALUES ('0001-J.PROG','Schmidt','Michael') [21S02-46]
	at org.h2.message.Message.addSQL(Message.java:348)
	at org.h2.command.Parser.prepareCommand(Parser.java:213)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:966)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:105)
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:603)
	at de.oio.aufbau.jdbc.ExtendedJdbc.doBatch(ExtendedJdbc.java:96)
	at de.oio.aufbau.jdbc.ExtendedJdbc.main(ExtendedJdbc.java:189)
Caused by: org.h2.jdbc.JdbcSQLException: Column count does not match [21S02-46]
	at org.h2.message.Message.getSQLException(Message.java:65)
	at org.h2.message.Message.getSQLException(Message.java:47)
	at org.h2.message.Message.getSQLException(Message.java:86)
	at org.h2.command.dml.Insert.prepare(Insert.java:175)
	at org.h2.command.Parser.prepareCommand(Parser.java:193)
	... 7 more
05-25 18:02:52 jdbc[0]: SQLException
java.sql.BatchUpdateException
	at org.h2.jdbc.JdbcStatement.executeBatch(JdbcStatement.java:614)
	at de.oio.aufbau.jdbc.ExtendedJdbc.doBatch(ExtendedJdbc.java:96)
	at de.oio.aufbau.jdbc.ExtendedJdbc.main(ExtendedJdbc.java:189)
05-25 18:03:44 jdbc[1]: SQLException
org.h2.jdbc.JdbcSQLException: Column count does not match; SQL statement: INSERT INTO person VALUES ('0001-J.PROG','Zwink','Daniel') [21S02-46]
	at org.h2.message.Message.addSQL(Message.java:348)
	at org.h2.command.Parser.prepareCommand(Parser.java:213)
	at org.h2.engine.Session.prepareLocal(Session.java:173)
	at org.h2.engine.Session.prepareCommand(Session.java:155)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:966)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:143)
	at org.h2.server.web.AppThread.getResult(AppThread.java:941)
	at org.h2.server.web.AppThread.query(AppThread.java:611)
	at org.h2.server.web.AppThread.process(AppThread.java:71)
	at org.h2.server.web.WebServerThread.run(WebServerThread.java:127)
Caused by: org.h2.jdbc.JdbcSQLException: Column count does not match [21S02-46]
	at org.h2.message.Message.getSQLException(Message.java:65)
	at org.h2.message.Message.getSQLException(Message.java:47)
	at org.h2.message.Message.getSQLException(Message.java:86)
	at org.h2.command.dml.Insert.prepare(Insert.java:175)
	at org.h2.command.Parser.prepareCommand(Parser.java:193)
	... 8 more
05-25 18:11:27 database: opening C:\Java\h2-1.0\data\aufbau
org.h2.jdbc.JdbcSQLException: Database may be already open: Locked by another process [90020-46]
	at org.h2.message.Message.getSQLException(Message.java:65)
	at org.h2.message.Message.getSQLException(Message.java:47)
	at org.h2.store.FileLock.error(FileLock.java:310)
	at org.h2.store.FileLock.lockFile(FileLock.java:171)
	at org.h2.store.FileLock.lock(FileLock.java:65)
	at org.h2.engine.Database.open(Database.java:423)
	at org.h2.engine.Database.<init>(Database.java:378)
	at org.h2.engine.Engine.openSession(Engine.java:49)
	at org.h2.engine.Engine.getSession(Engine.java:92)
	at org.h2.engine.Session.createSession(Session.java:140)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:923)
	at org.h2.Driver.connect(Driver.java:52)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at de.oio.aufbau.jdbc.ExtendedJdbc.openConnection(ExtendedJdbc.java:173)
	at de.oio.aufbau.jdbc.ExtendedJdbc.doScrollableResultSet(ExtendedJdbc.java:23)
	at de.oio.aufbau.jdbc.ExtendedJdbc.main(ExtendedJdbc.java:195)
05-25 18:25:00 database: opening C:\Java\h2-1.0\data\aufbau
org.h2.jdbc.JdbcSQLException: Database may be already open: Locked by another process [90020-46]
	at org.h2.message.Message.getSQLException(Message.java:65)
	at org.h2.message.Message.getSQLException(Message.java:47)
	at org.h2.store.FileLock.error(FileLock.java:310)
	at org.h2.store.FileLock.lockFile(FileLock.java:171)
	at org.h2.store.FileLock.lock(FileLock.java:65)
	at org.h2.engine.Database.open(Database.java:423)
	at org.h2.engine.Database.<init>(Database.java:378)
	at org.h2.engine.Engine.openSession(Engine.java:49)
	at org.h2.engine.Engine.getSession(Engine.java:92)
	at org.h2.engine.Session.createSession(Session.java:140)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:923)
	at org.h2.Driver.connect(Driver.java:52)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at de.oio.aufbau.jdbc.SimpleSelect.main(SimpleSelect.java:22)
05-25 18:25:25 database: opening C:\Java\h2-1.0\data\aufbau
org.h2.jdbc.JdbcSQLException: Database may be already open: Locked by another process [90020-46]
	at org.h2.message.Message.getSQLException(Message.java:65)
	at org.h2.message.Message.getSQLException(Message.java:47)
	at org.h2.store.FileLock.error(FileLock.java:310)
	at org.h2.store.FileLock.lockFile(FileLock.java:171)
	at org.h2.store.FileLock.lock(FileLock.java:65)
	at org.h2.engine.Database.open(Database.java:423)
	at org.h2.engine.Database.<init>(Database.java:378)
	at org.h2.engine.Engine.openSession(Engine.java:49)
	at org.h2.engine.Engine.getSession(Engine.java:92)
	at org.h2.engine.Session.createSession(Session.java:140)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:923)
	at org.h2.Driver.connect(Driver.java:52)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at de.oio.aufbau.jdbc.SimpleSelect.main(SimpleSelect.java:22)
05-25 18:27:19 database: opening C:\Java\h2-1.0\data\aufbau
org.h2.jdbc.JdbcSQLException: Database may be already open: Locked by another process [90020-46]
	at org.h2.message.Message.getSQLException(Message.java:65)
	at org.h2.message.Message.getSQLException(Message.java:47)
	at org.h2.store.FileLock.error(FileLock.java:310)
	at org.h2.store.FileLock.lockFile(FileLock.java:171)
	at org.h2.store.FileLock.lock(FileLock.java:65)
	at org.h2.engine.Database.open(Database.java:423)
	at org.h2.engine.Database.<init>(Database.java:378)
	at org.h2.engine.Engine.openSession(Engine.java:49)
	at org.h2.engine.Engine.getSession(Engine.java:92)
	at org.h2.engine.Session.createSession(Session.java:140)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:923)
	at org.h2.Driver.connect(Driver.java:52)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at de.oio.aufbau.jdbc.SimpleSelect.main(SimpleSelect.java:22)
05-25 18:36:11 database: opening C:\Java\h2-1.0\data\aufbau
org.h2.jdbc.JdbcSQLException: Database may be already open: Locked by another process [90020-46]
	at org.h2.message.Message.getSQLException(Message.java:65)
	at org.h2.message.Message.getSQLException(Message.java:47)
	at org.h2.store.FileLock.error(FileLock.java:310)
	at org.h2.store.FileLock.lockFile(FileLock.java:171)
	at org.h2.store.FileLock.lock(FileLock.java:65)
	at org.h2.engine.Database.open(Database.java:423)
	at org.h2.engine.Database.<init>(Database.java:378)
	at org.h2.engine.Engine.openSession(Engine.java:49)
	at org.h2.engine.Engine.getSession(Engine.java:92)
	at org.h2.engine.Session.createSession(Session.java:140)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:923)
	at org.h2.Driver.connect(Driver.java:52)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at de.oio.aufbau.jdbc.SimpleSelect.main(SimpleSelect.java:22)
05-29 15:17:28 database: opening C:\Java\h2-1.0\data\aufbau
org.h2.jdbc.JdbcSQLException: Database may be already open: Locked by another process [90020-46]
	at org.h2.message.Message.getSQLException(Message.java:65)
	at org.h2.message.Message.getSQLException(Message.java:47)
	at org.h2.store.FileLock.error(FileLock.java:310)
	at org.h2.store.FileLock.lockFile(FileLock.java:171)
	at org.h2.store.FileLock.lock(FileLock.java:65)
	at org.h2.engine.Database.open(Database.java:423)
	at org.h2.engine.Database.<init>(Database.java:378)
	at org.h2.engine.Engine.openSession(Engine.java:49)
	at org.h2.engine.Engine.getSession(Engine.java:92)
	at org.h2.engine.Session.createSession(Session.java:140)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:923)
	at org.h2.Driver.connect(Driver.java:52)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at de.oio.aufbau.jdbc.ExtendedJdbc.openConnection(ExtendedJdbc.java:203)
	at de.oio.aufbau.jdbc.ExtendedJdbc.doScrollResultSet(ExtendedJdbc.java:23)
	at de.oio.aufbau.jdbc.ExtendedJdbc.main(ExtendedJdbc.java:225)
05-29 15:18:53 database: opening C:\Java\h2-1.0\data\aufbau
org.h2.jdbc.JdbcSQLException: Database may be already open: Locked by another process [90020-46]
	at org.h2.message.Message.getSQLException(Message.java:65)
	at org.h2.message.Message.getSQLException(Message.java:47)
	at org.h2.store.FileLock.error(FileLock.java:310)
	at org.h2.store.FileLock.lockFile(FileLock.java:171)
	at org.h2.store.FileLock.lock(FileLock.java:65)
	at org.h2.engine.Database.open(Database.java:423)
	at org.h2.engine.Database.<init>(Database.java:378)
	at org.h2.engine.Engine.openSession(Engine.java:49)
	at org.h2.engine.Engine.getSession(Engine.java:92)
	at org.h2.engine.Session.createSession(Session.java:140)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:923)
	at org.h2.Driver.connect(Driver.java:52)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at de.oio.aufbau.jdbc.ExtendedJdbc.openConnection(ExtendedJdbc.java:203)
	at de.oio.aufbau.jdbc.ExtendedJdbc.doScrollResultSet(ExtendedJdbc.java:23)
	at de.oio.aufbau.jdbc.ExtendedJdbc.main(ExtendedJdbc.java:225)
